#!/usr/bin/env node
// Assemble the exact set of files served at https://akmalariq.dev into ./dist
//
// Why this exists: the site is deployed from the repo root, but the repo root
// also contains sources (blog-src/, node_modules/, docs) that must never be
// served. Instead of relying on ignore semantics, we build an explicit
// whitelist of what ships, and point the Pages "build output directory" at it.

import { cp, mkdir, rm, readdir, stat, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const OUT = join(ROOT, "dist");

const ENTRIES = [
  "index.html",
  "404.html", // disables Pages' SPA fallback → real 404s
  "_headers", // security + cache headers (Pages reads this from the output dir)
  "robots.txt",
  "sitemap.xml",
  "og.png",
  "cv.pdf", // master CV, copied from the Master/ pipeline
  "blog", // generated by `astro build` in blog-src/
  "projects", // case-study pages + their data (Jakarta map, earthquake)
  "demo", // sample report page
  "css",
  "fonts", // self-hosted woff2
  "js",
  "data",
];

// Root-level single files that should ship as-is (e.g. search-console
// verification HTML files), excluding build/config/markdown.
const ASSET_FILE = /\.(html|txt|xml|ico|png|svg|webp|jpg|jpeg|woff2?)$/i;
const SKIP_FILE = /^(package\.json|wrangler\.jsonc|sitemap\.xml|robots\.txt)$/i;

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  for (const entry of ENTRIES) {
    const src = join(ROOT, entry);
    if (!existsSync(src)) {
      console.warn(`  ! missing, skipped: ${entry}`);
      continue;
    }
    await cp(src, join(OUT, entry), { recursive: true });
    console.log(`  + ${entry}`);
  }

  await pruneAstroInternals();
  await minifyCssDir(join(OUT, "css"));
  await injectAnalytics();
  await versionAssets();

  // root-level loose files (search console tokens etc.)
  for (const name of await readdir(ROOT)) {
    if (ENTRIES.includes(name)) continue;
    if (name.startsWith(".")) continue;
    if (SKIP_FILE.test(name)) continue;
    if (!ASSET_FILE.test(name)) continue;
    const s = await stat(join(ROOT, name));
    if (!s.isFile()) continue;
    await cp(join(ROOT, name), join(OUT, name));
    console.log(`  + ${name}`);
  }

  console.log(`\nAssembled ${OUT}`);
}

// Conservative CSS minifier: strips comments and collapses whitespace.
// Deliberately does not rewrite values, so hand-written CSS stays safe.
function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{};:,>])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();
}

// Cloudflare Pages applies its own 4-hour Cache-Control to non-hashed assets and
// ignores Cache-Control set in _headers. Rather than fight it, version the URL:
// every /css and /js reference gets ?v=<content hash>, so a changed file is a
// new URL and visitors can never serve a stale stylesheet.
async function versionAssets() {
  const versions = new Map();

  const collect = async (dir, urlBase) => {
    if (!existsSync(dir)) return;
    for (const name of await readdir(dir)) {
      const full = join(dir, name);
      const info = await stat(full);
      if (info.isDirectory()) {
        await collect(full, `${urlBase}${name}/`);
        continue;
      }
      if (!/\.(css|js)$/.test(name)) continue;
      const hash = createHash("sha256").update(await readFile(full)).digest("hex").slice(0, 8);
      versions.set(`${urlBase}${name}`, `${urlBase}${name}?v=${hash}`);
    }
  };

  await collect(join(OUT, "css"), "/css/");
  await collect(join(OUT, "js"), "/js/");

  let rewritten = 0;
  const walk = async (dir) => {
    for (const name of await readdir(dir)) {
      const full = join(dir, name);
      const info = await stat(full);
      if (info.isDirectory()) {
        await walk(full);
        continue;
      }
      if (!name.endsWith(".html")) continue;

      const rel = full.slice(OUT.length + 1);
      const depth = rel.split("/").length - 1;
      let html = await readFile(full, "utf8");

      html = html.replace(/(href|src)="([^"]+\.(?:css|js))"/g, (match, attr, url) => {
        // Already-hashed build output (the blog's /blog/_assets/*) is left alone.
        if (url.startsWith("/blog/_assets/")) return match;
        const key = url.startsWith("/") ? url : depth === 0 ? `/${url}` : url;
        const versioned = versions.get(key);
        return versioned ? `${attr}="${versioned}"` : match;
      });

      if (html !== (await readFile(full, "utf8"))) {
        await writeFile(full, html);
        rewritten++;
      }
    }
  };
  await walk(OUT);
  console.log(`  v ${versions.size} assets versioned across ${rewritten} pages`);
}

async function minifyCssDir(dir) {
  if (!existsSync(dir)) return;
  let saved = 0;
  for (const name of await readdir(dir)) {
    if (!name.endsWith(".css")) continue;
    const file = join(dir, name);
    const before = await readFile(file, "utf8");
    const after = minifyCss(before);
    await writeFile(file, after);
    saved += before.length - after.length;
    console.log(`  ~ ${name}  ${(before.length / 1024).toFixed(1)} → ${(after.length / 1024).toFixed(1)} KB`);
  }
  if (saved > 0) console.log(`  = css saved ${(saved / 1024).toFixed(1)} KB`);
}

// Astro writes a few non-public artifacts into the output dir (type
// declarations, SSR chunks, route manifest). They must never be served.
async function pruneAstroInternals() {
  const blogOut = join(OUT, "blog");
  if (!existsSync(blogOut)) return;

  for (const name of ["astro", "chunks"]) {
    const target = join(blogOut, name);
    if (existsSync(target)) {
      await rm(target, { recursive: true, force: true });
      console.log(`  - blog/${name} (internal)`);
    }
  }
  for (const name of await readdir(blogOut)) {
    if (/^manifest_.*\.mjs$/.test(name)) {
      await rm(join(blogOut, name), { force: true });
      console.log(`  - blog/${name} (internal)`);
    }
  }
}


// Inject Google Tag Manager (or a direct GA4 tag) into every assembled HTML
// page, plus the first-party analytics helper. IDs come from data/analytics.json
// or the GTM_ID / GA4_ID environment variables. When neither is set, nothing is
// injected, so the site ships clean.
const ANALYTICS_MARKER = "<!-- analytics:akmal -->";

async function loadAnalyticsConfig() {
  let config = { gtmId: "", ga4Id: "" };
  const file = join(ROOT, "data", "analytics.json");
  if (existsSync(file)) {
    try {
      config = { ...config, ...JSON.parse(await readFile(file, "utf8")) };
    } catch (err) {
      console.warn(`  ! data/analytics.json unreadable: ${err.message}`);
    }
  }
  return {
    gtmId: (process.env.GTM_ID || config.gtmId || "").trim(),
    ga4Id: (process.env.GA4_ID || config.ga4Id || "").trim(),
  };
}

function gtmHead(gtmId) {
  return `${ANALYTICS_MARKER}
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${gtmId}');</script>`;
}

function gtmBody(gtmId) {
  return `<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=${gtmId}" height="0" width="0" style="display:none;visibility:hidden" title="Google Tag Manager"></iframe></noscript>`;
}

function ga4Head(ga4Id) {
  return `${ANALYTICS_MARKER}
    <script async src="https://www.googletagmanager.com/gtag/js?id=${ga4Id}"></script>
    <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${ga4Id}');</script>`;
}

async function injectAnalytics() {
  const { gtmId, ga4Id } = await loadAnalyticsConfig();
  if (!gtmId && !ga4Id) {
    console.log("  i analytics not configured (set data/analytics.json, or GTM_ID / GA4_ID)");
    return;
  }

  const headSnippet = gtmId ? gtmHead(gtmId) : ga4Head(ga4Id);
  const bodySnippet = gtmId ? gtmBody(gtmId) : "";
  const helper = `<script src="/js/analytics.js" defer></script>`;

  let pages = 0;
  const walk = async (dir) => {
    for (const name of await readdir(dir)) {
      const full = join(dir, name);
      const info = await stat(full);
      if (info.isDirectory()) {
        await walk(full);
        continue;
      }
      if (!name.endsWith(".html")) continue;

      let html = await readFile(full, "utf8");
      if (html.includes(ANALYTICS_MARKER) || !/<\/head>/i.test(html)) continue;

      html = html.replace(/<\/head>/i, `${headSnippet}\n    ${helper}\n</head>`);
      if (bodySnippet) {
        html = html.replace(/(<body[^>]*>)/i, `$1\n${bodySnippet}`);
      }
      await writeFile(full, html);
      pages++;
    }
  };
  await walk(OUT);
  console.log(
    `  + analytics injected on ${pages} pages (${gtmId ? `GTM ${gtmId}` : `GA4 ${ga4Id}`})`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
