#!/usr/bin/env node
// Assemble the exact set of files served at https://akmalariq.dev into ./dist
//
// Why this exists: the site is deployed from the repo root, but the repo root
// also contains sources (blog-src/, node_modules/, docs) that must never be
// served. Instead of relying on ignore semantics, we build an explicit
// whitelist of what ships, and point the Pages "build output directory" at it.

import { cp, mkdir, rm, readdir, stat, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const OUT = join(ROOT, "dist");

const ENTRIES = [
  "index.html",
  "404.html", // disables Pages' SPA fallback → real 404s
  "_headers", // security + cache headers (Pages reads this from the output dir)
  "robots.txt",
  "sitemap.xml",
  "og.png",
  "cv.pdf", // master CV, copied from the Master/ pipeline
  "blog", // generated by `astro build` in blog-src/
  "projects", // case-study pages + their data (Jakarta map, earthquake)
  "demo", // sample report page
  "css",
  "fonts", // self-hosted woff2
  "js",
  "data",
];

// Root-level single files that should ship as-is (e.g. search-console
// verification HTML files), excluding build/config/markdown.
const ASSET_FILE = /\.(html|txt|xml|ico|png|svg|webp|jpg|jpeg|woff2?)$/i;
const SKIP_FILE = /^(package\.json|wrangler\.jsonc|sitemap\.xml|robots\.txt)$/i;

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  for (const entry of ENTRIES) {
    const src = join(ROOT, entry);
    if (!existsSync(src)) {
      console.warn(`  ! missing, skipped: ${entry}`);
      continue;
    }
    await cp(src, join(OUT, entry), { recursive: true });
    console.log(`  + ${entry}`);
  }

  await pruneAstroInternals();
  await minifyCssDir(join(OUT, "css"));
  await versionAssets();

  // root-level loose files (search console tokens etc.)
  for (const name of await readdir(ROOT)) {
    if (ENTRIES.includes(name)) continue;
    if (name.startsWith(".")) continue;
    if (SKIP_FILE.test(name)) continue;
    if (!ASSET_FILE.test(name)) continue;
    const s = await stat(join(ROOT, name));
    if (!s.isFile()) continue;
    await cp(join(ROOT, name), join(OUT, name));
    console.log(`  + ${name}`);
  }

  console.log(`\nAssembled ${OUT}`);
}

// Conservative CSS minifier: strips comments and collapses whitespace.
// Deliberately does not rewrite values, so hand-written CSS stays safe.
function minifyCss(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{};:,>])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();
}

// Cloudflare Pages applies its own 4-hour Cache-Control to non-hashed assets and
// ignores Cache-Control set in _headers. Rather than fight it, version the URL:
// every /css and /js reference gets ?v=<content hash>, so a changed file is a
// new URL and visitors can never serve a stale stylesheet.
async function versionAssets() {
  const versions = new Map();

  const collect = async (dir, urlBase) => {
    if (!existsSync(dir)) return;
    for (const name of await readdir(dir)) {
      const full = join(dir, name);
      const info = await stat(full);
      if (info.isDirectory()) {
        await collect(full, `${urlBase}${name}/`);
        continue;
      }
      if (!/\.(css|js)$/.test(name)) continue;
      const hash = createHash("sha256").update(await readFile(full)).digest("hex").slice(0, 8);
      versions.set(`${urlBase}${name}`, `${urlBase}${name}?v=${hash}`);
    }
  };

  await collect(join(OUT, "css"), "/css/");
  await collect(join(OUT, "js"), "/js/");

  let rewritten = 0;
  const walk = async (dir) => {
    for (const name of await readdir(dir)) {
      const full = join(dir, name);
      const info = await stat(full);
      if (info.isDirectory()) {
        await walk(full);
        continue;
      }
      if (!name.endsWith(".html")) continue;

      const rel = full.slice(OUT.length + 1);
      const depth = rel.split("/").length - 1;
      let html = await readFile(full, "utf8");

      html = html.replace(/(href|src)="([^"]+\.(?:css|js))"/g, (match, attr, url) => {
        // Already-hashed build output (the blog's /blog/_assets/*) is left alone.
        if (url.startsWith("/blog/_assets/")) return match;
        const key = url.startsWith("/") ? url : depth === 0 ? `/${url}` : url;
        const versioned = versions.get(key);
        return versioned ? `${attr}="${versioned}"` : match;
      });

      if (html !== (await readFile(full, "utf8"))) {
        await writeFile(full, html);
        rewritten++;
      }
    }
  };
  await walk(OUT);
  console.log(`  v ${versions.size} assets versioned across ${rewritten} pages`);
}

async function minifyCssDir(dir) {
  if (!existsSync(dir)) return;
  let saved = 0;
  for (const name of await readdir(dir)) {
    if (!name.endsWith(".css")) continue;
    const file = join(dir, name);
    const before = await readFile(file, "utf8");
    const after = minifyCss(before);
    await writeFile(file, after);
    saved += before.length - after.length;
    console.log(`  ~ ${name}  ${(before.length / 1024).toFixed(1)} → ${(after.length / 1024).toFixed(1)} KB`);
  }
  if (saved > 0) console.log(`  = css saved ${(saved / 1024).toFixed(1)} KB`);
}

// Astro writes a few non-public artifacts into the output dir (type
// declarations, SSR chunks, route manifest). They must never be served.
async function pruneAstroInternals() {
  const blogOut = join(OUT, "blog");
  if (!existsSync(blogOut)) return;

  for (const name of ["astro", "chunks"]) {
    const target = join(blogOut, name);
    if (existsSync(target)) {
      await rm(target, { recursive: true, force: true });
      console.log(`  - blog/${name} (internal)`);
    }
  }
  for (const name of await readdir(blogOut)) {
    if (/^manifest_.*\.mjs$/.test(name)) {
      await rm(join(blogOut, name), { force: true });
      console.log(`  - blog/${name} (internal)`);
    }
  }
}


main().catch((err) => {
  console.error(err);
  process.exit(1);
});
