#!/usr/bin/env node
// Assemble the exact set of files served at https://akmalariq.dev into ./dist
//
// Why this exists: the site is deployed from the repo root, but the repo root
// also contains sources (blog-src/, node_modules/, docs) that must never be
// served. Instead of relying on ignore semantics, we build an explicit
// whitelist of what ships, and point the Pages "build output directory" at it.

import { cp, mkdir, rm, readdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const OUT = join(ROOT, "dist");

const ENTRIES = [
  "index.html",
  "404.html", // disables Pages' SPA fallback → real 404s
  "robots.txt",
  "sitemap.xml",
  "blog", // generated by `astro build` in blog-src/
  "css",
  "js",
  "data",
  "images",
];

// Root-level single files that should ship as-is (e.g. search-console
// verification HTML files), excluding build/config/markdown.
const ASSET_FILE = /\.(html|txt|xml|ico|png|svg|webp|jpg|jpeg|woff2?)$/i;
const SKIP_FILE = /^(package\.json|wrangler\.jsonc|sitemap\.xml|robots\.txt)$/i;

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  for (const entry of ENTRIES) {
    const src = join(ROOT, entry);
    if (!existsSync(src)) {
      console.warn(`  ! missing, skipped: ${entry}`);
      continue;
    }
    await cp(src, join(OUT, entry), { recursive: true });
    console.log(`  + ${entry}`);
  }

  await pruneAstroInternals();

  // root-level loose files (search console tokens etc.)
  for (const name of await readdir(ROOT)) {
    if (ENTRIES.includes(name)) continue;
    if (name.startsWith(".")) continue;
    if (SKIP_FILE.test(name)) continue;
    if (!ASSET_FILE.test(name)) continue;
    const s = await stat(join(ROOT, name));
    if (!s.isFile()) continue;
    await cp(join(ROOT, name), join(OUT, name));
    console.log(`  + ${name}`);
  }

  console.log(`\nAssembled ${OUT}`);
}

// Astro writes a few non-public artifacts into the output dir (type
// declarations, SSR chunks, route manifest). They must never be served.
async function pruneAstroInternals() {
  const blogOut = join(OUT, "blog");
  if (!existsSync(blogOut)) return;

  for (const name of ["astro", "chunks"]) {
    const target = join(blogOut, name);
    if (existsSync(target)) {
      await rm(target, { recursive: true, force: true });
      console.log(`  - blog/${name} (internal)`);
    }
  }
  for (const name of await readdir(blogOut)) {
    if (/^manifest_.*\.mjs$/.test(name)) {
      await rm(join(blogOut, name), { force: true });
      console.log(`  - blog/${name} (internal)`);
    }
  }
}


main().catch((err) => {
  console.error(err);
  process.exit(1);
});
